dfdf

diff --git a/.github/workflows/deploy.yaml b/.github/workflows/deploy.yaml
--- a/.github/workflows/deploy.yaml
+++ b/.github/workflows/deploy.yaml
@@ -30,6 +30,10 @@ jobs:
         run: echo "All valid!"
       - name: Invalid environment
         if: steps.validate-cmd-deploy-params.outputs.valid == 'false'
-        run: echo "Invalid!"
+        run: 
+          echo "Invalid!"
+          exit 1
+      - name: Final message
+        run: echo "This is the end!"
       
         
